seed: 283

num_episodes: 50000
replay_buffer_size: 100000
gamma: 0.99
tau: 0.001
max_steps_without_reward: 200

noise: 1.0
noise_decay: 0.999
noise_min: 0.3

batch_size: 32
actor_lr: 0.001
critic_lr: 0.001

save_dir: ckpt
save_every: 500

render: true

plot: true
plot_interval: 80
