seed: 283

num_episodes: 50000
gamma: 0.99
max_steps_without_reward: 200
target_update_interval: 100

memory_size: 100000
memory_alpha: 0.6
memory_beta: 0.4

epsilon: 1.0
epsilon_decay: 0.995
epsilon_min: 0.1

batch_size: 16
lr: 0.001

save_dir: ckpt
save_every: 100

render: true

plot: true
plot_interval: 80
